# The main config file for your Jekyll template

# Site settings
title: Allison Traylor               # used for the html title of every page
desc: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: allisontraylor.com      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

logo_filename: rice-logo.svg

# Meta settings
email: allison.m.traylor@rice.edu
author: Allison Traylor
linkedin_username: atraylor

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: About
    url: /about/
    desc: Learn about me
  - title: Research
    url: /research/
    desc: My published research
  - title: Travel
    url: /travel/
    desc: Travel tips for some of my favorite places

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
plugins:
  - jekyll-paginate

